### ISSUE TITLE
Arm's ProgressBar.value is breaking tests.

### ISSUE THREAD

**Issue by AmadNinja** [RaihanSharif/Pediatric_game#21]
In the ArmTesting class I call the method Arm.startProcess() which calls IncreaseProgress() which calls progressBar.value = CalculateProgress() which somehow breaks the test and returns a 
'[Exception] NullReferenceException: Object reference not set to an instance of an object'. 

This problem must have something to do with the fact the progressBar's value is something that is from the progressBar class itself which is a MonoBehaviour class.

**Comment by abdurmasood** [comment]
@Amine1998 you wrote the code for the progress bar, you might want to help amedeo out in this one
